### ISSUE TITLE
Search bar dropdown selection not working on Chrome desktop

### ISSUE THREAD

**Issue by jmccloskey108** [ehedaya/emilstabs.org#141]
FYI when I click on a song from the dropdown autofill list under the search bar, nothing seems to happen in recent months on Chrome desktop. Mobile and Microsoft Edge both seem to work.

**Comment by ehedaya** [comment]
Does it work if you use the down arrow key to select, then press ENTER?  It should work if you click but it would help to debug if you can share whether that does work.

**Comment by ColonelForbin108** [comment]
No that doesn't seem to work either, same behavior as clicking. The text
field populates, but when I hit enter again nothing happens, and when I
click "go" the the text field gets blanked out without redirecting to a
different page.
