### ISSUE TITLE
Re: Winterqueen

### ISSUE THREAD

**Issue by CamelWalkr** [ehedaya/emilstabs.org#143]
this accentuates the sound of pages keys before solo

e---14--          --14---
B---12--          --12---
G---11--          --11---
D-------          ---9---
A-------          -------
E------ or even------

**Comment by ehedaya** [comment]
Thanks for you suggestion, it'd be helpful if you could edit the file directly and submit a pull request:

https://github.com/ehedaya/emilstabs.org/blob/master/files/tabs/Winterqueen.txt

Thanks!

Emil
