### ISSUE TITLE
Re: Light

### ISSUE THREAD

**Issue by mplunket** [ehedaya/emilstabs.org#147]
Not sure if your edits are correct. Watch this (https://www.youtube.com/watch?v=uWh1ur7B5FI) and it looks like Trey is playing A/E, A/G#m for the "..and I'm left in the now, with a wondrous glow" part.

**Comment by ehedaya** [comment]
Sorry I didn't see this sooner, feel free to open the file and click "Edit" to make the edits you think are appropriate

https://github.com/ehedaya/emilstabs.org/blob/master/files/tabs/Light.txt

Emil
