### ISSUE TITLE
8/22/15 BDTNL Trey Solo closeup clip

### ISSUE THREAD

**Issue by MattyItsIced** [ehedaya/emilstabs.org#149]
I love this solo from Trey and there is a video posted on Instagram of him playing, could be a cool thing to add to the Trey Playing section of the site!

https://www.instagram.com/p/BWQCbhUFWPB/

**Comment by ehedaya** [comment]
Nice video! I agree it'd be nice but the section just links out to a YouTube channel.  Appreciate you sending it over but I'm not sure where I'd fit it in 🤔
