### ISSUE TITLE
I have no coding experience. I can’t follow the guide because it doesn’t describe tab formatting. Why is this so difficult?

### ISSUE THREAD

**Issue by mbpolatin** [ehedaya/emilstabs.org#175]

**Comment by ehedaya** [comment]
Sorry to hear you're having trouble, were you looking to make an edit or submit a new transcription?

**Comment by mbpolatin** [comment]
Hi! I wanted to put in a new submission for one of treys new songs. I have typed it out in word but does that not translate into the coding software?
Thanks!
Ben

**Comment by mbpolatin** [comment]
I’ve still been trying but as soon as I see any code my mind gets frustrated. Could I just send to you? No rush. It’s I never needed you like this before. One of treys quarantine songs that rocks.
Best
Ben

**Comment by mbpolatin** [comment]
Is there a way to do it myself with ought knows any coding? Im sorry to keep bothering you about this.
Thanks
Ben

> On Mar 31, 2020, at 7:29 AM, The Argus <theargus2@gmail.com> wrote:
> 

﻿
I’ve still been trying but as soon as I see any code my mind gets frustrated. Could I just send to you? No rush. It’s I never needed you like this before. One of treys quarantine songs that rocks.
Best
Ben

**Comment by ehedaya** [comment]
Hey Ben,  Sorry it's been difficult. 

Sure, feel free to email it. If you open Notepad or even https://pastebin.com/ and type it out, you can paste it here, or share a link. Whatever is easier.

Thanks,

Emil

**Comment by mbpolatin** [comment]
Emil,
Hey, no problem at ALL. We’re living in different times. On the upside we’ve got trey putting out some strong material directly to fans. That’s the phish fans glass half full.

I wanted to make sure no one submitted this song already so that I didn’t tab it out for “nothing”:
I Never Needed You Like This Before.

Peace and stay safe. Thanks, in a way your site has taught me how to play the guitar to an elevated level and I appreciate all of your hard work.
Best,
Ben

> On Apr 10, 2020, at 8:28 PM, Emil H. <notifications@github.com> wrote:
> 

﻿
Hey Ben, Sorry it's been difficult.

Sure, feel free to email it. If you open Notepad or even https://pastebin.com/ and type it out, you can paste it here, or share a link. Whatever is easier.

Thanks,

Emil

**Comment by mbpolatin** [comment]
I’m REALLY sorry to bother you with this again. I uploaded the song but I can’t find it anywhere. Are you able to see whether it’s going to the site or if I am not authorized?
Best,
Ben

**Comment by mbpolatin** [comment]
Hi I just wanted to check how to get my tab listed. I think I did everything correctly and that it is in the right place. It’s I Never Needed You Like this Before.
Thank you!

> On Apr 10, 2020, at 8:28 PM, Emil H. <notifications@github.com> wrote:
> 

﻿
Hey Ben, Sorry it's been difficult.

Sure, feel free to email it. If you open Notepad or even https://pastebin.com/ and type it out, you can paste it here, or share a link. Whatever is easier.

Thanks,

Emil

**Comment by mbpolatin** [comment]
Hi!
I’m sorry to bother you. I just wanted to see how I can get this file into the main tab list.
https://github.com/mbpolatin/emilstabs.org/blob/master/files/tabs/I%20never%20needed%20you%20like%20this%20before

Thanks!
Ben

**Comment by mbpolatin** [comment]
Hi,
I’m sorry for bothering you again about this. I wanted to see if my tab for the trey song could be posted especially since I spent a while on it and it’s correct. I thought I did the right procedure from guithub but I may not have.
Best,
Ben

**Comment by ehedaya** [comment]
Hi Ben. Sorry for the delay. It should be live now. Thanks for contributing and being patient. 

Emil
