### ISSUE TITLE
Pebbles and Marbles full re-write

### ISSUE THREAD

**Issue by jonnywoz** [ehedaya/emilstabs.org#182]
Hey - so the Pebbles and Marbles tab on the site is a very, very basic outline of the song.  It ignores two main pieces to Trey's original, acoustic arrangement:  alternating thumb fingerstyle and a change in tuning (EAEGBE) - which affects all the chords and shapes.

I figure my tab can be included as an update, overwrite, or as an "acoustic version"

file is attached as .txt -  let me know if there's a better way.  copy / paste in this body didn't look right because the font isn't monospaced.
[Pebbles and Marbles.txt](https://github.com/ehedaya/emilstabs.org/files/4465476/Pebbles.and.Marbles.txt)

**Comment by jonnywoz** [comment]
is anybody there?  did i use this GitHub thing correctly?

**Comment by livercup** [comment]
thanks for that

**Comment by ehedaya** [comment]
Hi @jonnywoz thanks for sharing!  I’ll try to copy it in shortly. 

Emil
