### ISSUE TITLE
Re: Winterqueen

### ISSUE THREAD

**Issue by Redchamp22** [ehedaya/emilstabs.org#224]
Such a fun song to play. I add an E on the “to rule those who walk on land” so that A hits on those, E on walk, and back to B on land, and then repeat that pattern each verse. Just my 2 cents. Thanks for all the tabs and chords!

**Comment by vibrato86** [comment]
Couldn't agree more. A fun and amazing tune the jam on this song can end up anywhere!

**Comment by ehedaya** [comment]
☺️
