### ISSUE TITLE
Hey Emil...  Just a fan with an idea for Emil's tabs

### ISSUE THREAD

**Issue by mrfisher2** [ehedaya/emilstabs.org#81]
I've been using your tabs site to create a series of YouTube videos that basically have aligned the tabs on your site, with Phish performances to create kinda "living tabs"

They use the annotation tool in YouTube, so unfortunately the tab instructions are only viewable on a desktop/laptop and not mobile.

Here is a link to the How to Phish Playlist that I've been working on
https://www.youtube.com/playlist?list=PL38ZwelW-Y3S_y7cioEMG66yFUVFwWIyJ

I noticed your site has a few videos of Trey playing, but thought this might be a fun addition to the site to help people learn Phish songs.

Just thought you might be interested!

Thanks,

Michael Fisher

**Comment by ehedaya** [comment]
Thanks, these are great! How do you envision incorporating them into the archive?

**Comment by mrfisher2** [comment]
I guess the easiest way of incorporating would be a simple link from the main page to the How to Phish videos page.  Perhaps it is as easy as adding a section at the top of the page where you have
"Guitar"  "Bass"  "Loops"  and a new section "Videos" that directs to the YouTube channel?

A little bit more work I'd guess would be making them searchable through your page.  Admittedly, I'm not very familiar with GitHub pages though.

**Comment by bradherman** [comment]
@mrfisher2 have you heard of soundslice?

http://soundslice.com/

See this as an example: https://www.soundslice.com/tabs/1867/phish-farmhouse-tab/

**Comment by ehedaya** [comment]
@mrfisher2 I haven't forgotten about this, just been very busy lately.  I want to add a link to your videos to the site. Thanks for your patience!

**Comment by mrfisher2** [comment]
@bradherman - Hey Brad, I have heard of soundslice, but haven't tried using their interface before.  I've opted for YouTube mostly because of it's ubiquity, and ease of use.  Have you made things in soundslice before?  I took a look at the Farmhouse video you sent.  Cool stuff :)

@ehedaya - Thanks man!  I appreciate your help!  I've been using your site to learn Phish tunes for a long time now!

**Comment by bradherman** [comment]
@mrfisher2 i started annotating a video a while back when they first launched but only did like 1 lick: https://www.soundslice.com/tabs/2222/lesson-7-the-style-of-trey-anastasio-tab/  -- pretty easy and straightforward
